/*

 SPRITES.C

 Tile Source File.

 Info:
  Form                 : Each tile separate.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

const unsigned char player_sprite[] = {0x38, 0x38, 0x38, 0x28, 0x38, 0x38,
                                       0x6C, 0x54, 0x44, 0x7C, 0x44, 0x38,
                                       0x28, 0x28, 0x28, 0x00};

/* End of SPRITES.C */
