//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_border_data_H
#define METASPRITE_border_data_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define border_data_TILE_ORIGIN 0
#define border_data_TILE_H 8
#define border_data_WIDTH 256
#define border_data_HEIGHT 224
#define border_data_TILE_COUNT 222
#define border_data_MAP_ATTRIBUTES 0
#define border_data_TILE_PALS 0

BANKREF_EXTERN(border_data)

extern const palette_color_t border_data_palettes[32];
extern const uint8_t border_data_tiles[7104];

extern const unsigned char border_data_map[1792];

#endif