/*

 SPRITES.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : GB-Compress.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char player_sprite[] = {0x02, 0x38, 0xC8, 0x10, 0x38, 0x38,
                                       0x44, 0x7C, 0x44, 0x7C, 0x44, 0x38,
                                       0x02, 0x28, 0x10, 0x00, 0x00};

/* End of SPRITES.C */
