const char *phrases[] = {
    "What's my favorite letter? I'm still deciding between R, I, and C.",
    "I left my peg in the freezer. Shiver me timbers!",
    "A pirate plunders the high seas. A pie-rat plunders the pantry.",
    "We set sail on the high seas at the kraken of dawn.",
    "Watch out for pirate ships; they're assailing vessels.",
    "You can abso-loot-ly trust me with the treasure map.",
    "Pirates are obsessed with being at sea. They're aqua-holics.",
    "Seeing a pirate ship in person is truly oar-inspiring.",
    // jokes
    "What's it called when two pirates draw? A stale-matey!",
    "Why did the pirate go to rehab? Because he got hooked!",
    "Why did the pirate quit his plundering ways? He was a pegleg in a square hole.",
    "What do you call a one-handed pirate who doesn't bathe? A dirty hooker!",
    "Why does a pirate name his dog The Plank? Because he walks The Plank.",
    "What does a pirate's dog do? Scallywag his tail!",
    "What do you call it when the crew of a pirate ship plots mutiny? A consipra-sea!",
    "Do pirates like to fight? Sword of...",
    "What grades do future pirates strive for in school? High C's!",
    "Why do pirates drink to excess? Pier pressure.",
    "Why don't pirates shower before they walk the plank? Because they'll just wash up on shore later.",
    "How do pirates know that they are pirates? They think, therefore they ARR!",
    "What happened when Bluebeard fell overboard in the Red Sea? He got marooned.",
    "What has 8 legs, 8 arms, and 8 eyes? 8 pirates!",
    "What do ye call a pirate with two eyes and two legs? A rookie.",
    "What did the ocean say to the pirate? Nothing - it just waved.",
    "Why does it take pirates so long to learn the alphabet? Because they spend years at C.",
    "What lies at the bottom of the ocean and twitches? A nervous wreck.",
    "How much did the pirate pay for his piercings? A buck an ear!",
    "How much did the pirate pay for his peg and hook? An arm and a leg!",
    "How do pirates prefer to communicate? Aye to aye.",
    "How do you make a pirate furious? Take away the P",
    "Why did nobody want to play cards with the pirate? Because he was standing on the deck.",
    "What did the pirate wear on Halloween? A pumpkin patch.",
};

const int phrase_len = sizeof(phrases) / sizeof(phrases[0]);
